export const KEYWORD_MAP: Record<string, string[]> = {
  restaurant: ["catering.restaurant"],
  restaurants: ["catering.restaurant"],
  cafe: ["catering.cafe"],
  cafes: ["catering.cafe"],
  coffee: ["catering.cafe"],
  bar: ["catering.bar"],
  bars: ["catering.bar"],
  pub: ["catering.pub"],
  ramen: ["catering.restaurant"],
  sushi: ["catering.restaurant"],
  fastfood: ["catering.fast_food"],
  bakery: ["commercial.food.bakery", "catering.restaurant"],
  
  hotel: ["accommodation.hotel"],
  hotels: ["accommodation.hotel"],
  motel: ["accommodation.motel"],
  hostel: ["accommodation.hostel"],
  inn: ["accommodation.guest_house"],
  ryokan: ["accommodation.hotel"],
  
  salon: ["service.beauty"],
  beauty: ["service.beauty"],
  hair: ["service.beauty"],
  spa: ["service.beauty"],
  barber: ["service.beauty"],
  massage: ["service.beauty"],
  bank: ["service.financial"],
  atm: ["service.financial.atm"],
  post: ["service.post"],
  police: ["service.police"],
  
  hospital: ["healthcare.hospital", "healthcare"],
  clinic: ["healthcare.clinic", "healthcare.doctor", "healthcare"],
  doctor: ["healthcare.doctor", "healthcare"],
  dentist: ["healthcare.dentist", "healthcare"],
  pharmacy: ["healthcare.pharmacy", "commercial.health_and_beauty.pharmacy"],
  
  school: ["education.school", "education"],
  university: ["education.university", "education"],
  college: ["education.college", "education"],
  kindergarten: ["education.kindergarten", "education"],
  
  supermarket: ["commercial.supermarket"],
  convenience: ["commercial.convenience"],
  grocery: ["commercial.supermarket"],
  mall: ["commercial.shopping_mall"],
  shopping: ["commercial.shopping_mall", "commercial.department_store"],
  clothing: ["commercial.clothing"],
  electronics: ["commercial.electronics"],
  books: ["commercial.books"],
  
  agency: ["office.estate_agent", "commercial.real_estate"],
  estate: ["office.estate_agent"],
};
